blogs/urls.py
from django.urls import path
from .views import BlogsView, BlogDetailView, CommentCreateView

app_name = 'blogs'

urlpatterns = [
    path('', BlogsView.as_view(), name='posts'),
    path('<int:pk>/post/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blogs.urls')),
    path('order/', include('orders.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, ContactView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact')
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView, wishlist_view, WishlistListView, update_cart_view

app_name = 'shop'

urlpatterns = [
    path('', ShopView.as_view(), name='home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('product/<int:pk>/wishlist', wishlist_view, name='wishlist'),
    path('wishlists/', WishlistListView.as_view(), name='wishlists'),
    path('add_cart/<int:id>/', update_cart_view, name='cart')
]

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


class AutherModel(models.Model):
    full_name = models.CharField(max_length=100, verbose_name=_('full name'))
    image = models.ImageField(upload_to='auther_images/', verbose_name=_('image'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('auther')
        verbose_name_plural = _('authers')


class PostTagModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    body = RichTextUploadingField(verbose_name=_('body'))
    main_image = models.ImageField(upload_to='main_images/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='banner/', verbose_name=_('banner'))
    auther = models.ForeignKey(AutherModel, related_name='posts', on_delete=models.RESTRICT)
    tag = models.ManyToManyField(PostTagModel, related_name='posts', verbose_name=_('tag'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return f"{self.title[:100]} ..."

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')


class CommentModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='comments', verbose_name=_('post'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='created at')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

shop/models.py
from django.contrib.auth import get_user_model
from django.db import models, IntegrityError
from django.db.models import Sum
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone

UserModel = get_user_model()


class CategoryModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categoies')


class ProductBrandModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('brand')
        verbose_name_plural = _('brands')


class ProductSizeModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('size')
        verbose_name_plural = _('sizes')


class ProductColorModel(models.Model):
    code = models.CharField(max_length=60, verbose_name=_('code'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('color')
        verbose_name_plural = _('colors')


class ProductTagModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class ProductModel(models.Model):
    title = models.CharField(max_length=60, verbose_name=_('title'))
    short_description = models.CharField(max_length=255, verbose_name=_('short description'))
    long_description = RichTextUploadingField(verbose_name=_('long description'))
    price = models.FloatField(verbose_name=_('price'))
    real_price = models.FloatField(verbose_name=_('real price'), default=0)
    sale = models.BooleanField(default=False, verbose_name=_('sale'))
    discount = models.PositiveSmallIntegerField(default=0, verbose_name=_('discount'))
    main_image = models.ImageField(upload_to='products/', verbose_name=_('main image'))
    category = models.ForeignKey(
        CategoryModel,
        related_name='products',
        on_delete=models.RESTRICT,
        verbose_name=_('category')
    )
    tag = models.ManyToManyField(
        ProductTagModel,
        related_name='products',
        verbose_name=_('tag')
    )
    size = models.ManyToManyField(
        ProductSizeModel,
        related_name='products',
        verbose_name=_('sizes')
    )
    color = models.ManyToManyField(
        ProductColorModel,
        related_name='products',
        verbose_name=_('colors')
    )
    brand = models.ForeignKey(
        ProductBrandModel,
        on_delete=models.RESTRICT,
        related_name='products',
        verbose_name=_('brands'),
        null=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def is_discount(self):
        return bool(self.discount)

    def new(self):
        return (timezone.now() - self.created_at).days <= 5

    @staticmethod
    def get_cart_info(request):
        cart = request.session.get('cart', [])
        if not cart:
            return 0, 0.0
        return len(cart), ProductModel.objects.filter(id__in=cart).aggregate(Sum('real_price'))['real_price__sum']

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')


class WishlistModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name=_('wishlists'), verbose_name=_('user'))
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, verbose_name=_('product'))

    @staticmethod
    def create_or_delete(user, product):
        try:
            return WishlistModel.objects.create(user=user, product=product)
        except IntegrityError:
            return WishlistModel.objects.get(user=user, product=product).delete()

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.product.title}"

    class Meta:
        verbose_name = _('wishlist')
        verbose_name_plural = _('wishlists')
        unique_together = 'user', 'product'

blogs/forms.py
from django import forms
from .models import CommentModel


class CommentModelForm(forms.ModelForm):

    class Meta:
        model = CommentModel
        exclude = ['post', 'created_at']

shop/forms.py
from django import forms
from .models import ProductColorModel


class ColorModelAdminForm(forms.ModelForm):
    code = forms.CharField(widget=forms.TextInput(attrs={'type': 'color'}))

    class Meta:
        model = ProductColorModel
        fields = '__all__'

blogs/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import PostModel
from .forms import CommentModelForm


class BlogsView(ListView):
    template_name = 'blog.html'

    def get_queryset(self):
        qs = PostModel.objects.order_by('-id')
        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__name=tag)
        return qs


class BlogDetailView(DetailView):
    model = PostModel
    template_name = 'blog-details.html'


class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs:detail', kwargs={'pk': self.kwargs.get('pk')})

shop/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Min, Max
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import ProductModel, CategoryModel, ProductTagModel, ProductColorModel, ProductBrandModel, \
    ProductSizeModel, WishlistModel


class ShopView(ListView):
    template_name = 'shop.html'
    paginate_by = 3

    def get_queryset(self):
        qs = ProductModel.objects.all()
        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(title__icontains=search)

        category = self.request.GET.get('cat')
        if category:
            qs = qs.filter(category_id=category)

        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(id=tag)

        brand = self.request.GET.get('brand')
        if brand:
            qs = qs.filter(brand=brand)

        size = self.request.GET.get('size')
        if size:
            qs = qs.filter(size=size)

        color = self.request.GET.get('color')
        if color:
            qs = qs.filter(color=color)

        sort = self.request.GET.get('sort')
        if sort == 'price':
            qs = qs.order_by('price')
        elif sort == '-price':
            qs = qs.order_by('-price')
        elif sort == 'sale':
            qs = qs.filter(sale=True)

        price = self.request.GET.get('price')
        if price:
            min, max = price.split(';')
            qs = qs.filter(real_price__gte=min, real_price__lte=max)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data['categories'] = CategoryModel.objects.all()
        data['tags'] = ProductTagModel.objects.all()
        data['brands'] = ProductBrandModel.objects.all()
        data['sizes'] = ProductSizeModel.objects.all()
        data['colors'] = ProductColorModel.objects.all()
        data['min_price'], data['max_price'] = ProductModel.objects.aggregate(Min('real_price'),
                                                                              Max('real_price')).values()

        return data


class ProductDetailView(DetailView):
    model = ProductModel
    template_name = 'shop-details.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data['products'] = ProductModel.objects.all().exclude(id=self.object.pk)[:4]

        return data


@login_required
def wishlist_view(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)
    WishlistModel.create_or_delete(request.user, product)

    return redirect(request.GET.get('next', '/'))


class WishlistListView(LoginRequiredMixin, ListView):
    template_name = 'wishlist.html'

    def get_queryset(self):
        return ProductModel.objects.filter(wishlistmodel__user_id=self.request.user)


def update_cart_view(request, id):
    cart = request.session.get('cart', [])

    if id in cart:
        cart.remove(id)
    else:
        cart.append(id)

    request.session['cart'] = cart
    return redirect(request.GET.get('next', '/'))

templates/blog-details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ object.title }}</h2>
                        <ul>
                            <li>By {{ object.auther.full_name }}</li>
                            <li>{{ object.created_at|date:'F d, Y' }}</li>
                            {% if object.comments.values %}
                                <li>{{ object.comments.values.count }} Comments</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ object.banner.url }}" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            <p>
                                {{ object.body|safe }}
                            </p>
                        </div>

                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ object.auther.image.url }}" alt="">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ object.auther.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in object.tag.all %}
                                            <a href="{% url 'blogs:posts' %}?tag={{ tag.name }}">#{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if object.get_previous_by_created_at %}
                                        <a href="{% url 'blogs:detail' pk=object.get_previous_by_created_at.pk %}"
                                           class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ object.get_previous_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if object.get_next_by_created_at %}
                                        <a href="{% url 'blogs:detail' pk=object.get_next_by_created_at.pk %}"
                                           class="blog__details__btns__item blog__details__btns__item--next">
                                            <p>Next Pod <span class="arrow_right"></span></p>
                                            <h5>{{ object.get_next_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            {% for comment in object.comments.values %}
                                <div class="row mb-3">
                                    <div class="col-6"><strong>{{ comment.name }}</strong></div>
                                    <div class="col-6 text-right">{{ comment.created_at|timesince }} ago</div>
                                    <div class="col-12 mt-2">{{ comment.comment }}</div>
                                </div>
                                <hr>
                            {% endfor %}
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:comment' pk=object.pk %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="email" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="comment" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->


{% endblock %}

templates/blog.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if request.GET %}
                        <h2>#{{ request.GET.tag }}</h2>
                    {% else %}
                        <h2>Our Blog</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for post in object_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ post.main_image.url }}"></div>
                            <div class="blog__item__text">
                                <span><img src="{% static 'img/icon/calendar.png' %}" alt=""> {{ post.created_at|date:'d F Y' }}</span>
                                <h5>{{ post.title|title|truncatewords:'5'}}</h5>
                                <a href="{% url 'blogs:detail' post.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/product_item.html
{% load static my_tags %}
<div class="product__item sale">
    <div class="product__item__pic set-bg"
         data-setbg="{{ product.main_image.url }}">
        {% if product.is_discount %}
            <span class="label">Sale</span>
        {% endif %}
        {% if product.new %}
            <span class="label new">New</span>
        {% endif %}
        <ul class="product__hover">
            {% if request.user.is_authenticated %}
                {% if product|is_wishlist:request %}
                    <li>
                        <a href="{% url 'shop:wishlist' pk=product.pk %}?next={{ request.path }}">
                            <img src="{% static 'img/img.png' %}" alt="">
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'shop:wishlist' pk=product.pk %}?next={{ request.path }}">
                            <img src="{% static 'img/icon/heart.png' %}" alt="">
                        </a>
                    </li>
                {% endif %}
            {% endif %}
            <li>
                <a href="{% url 'shop:detail' pk=product.pk %}">
                    <img src="{% static 'img/icon/search.png' %}" alt="">
                </a>
            </li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ product.title }}</h6>
        {% if product|is_cart:request %}
            <a href="{% url 'shop:cart' id=product.pk %}?next={{ request.path }}" class="add-cart">- Remove from Cart</a>
        {% else %}
            <a href="{% url 'shop:cart' id=product.pk %}?next={{ request.path }}" class="add-cart">+ Add To Cart</a>
        {% endif %}
        <div class="rating">
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>${{ product.real_price }} {% if product.is_discount %}
            <del class="text-secondary">{{ product.price }}</del>{% endif %}</h5>
        <div class="product__color__select">
            {% for color in product.color.all %}
                <label style="background-color: {{ color.code }}" for="{{ color.code }}">
                    <input type="radio" id="{{ color.code }}">
                </label>
            {% endfor %}
        </div>
    </div>
</div>

templates/shop_sidebar.html
{% load static %}
<div class="shop__sidebar">
    <div class="shop__sidebar__search">
        <form action="{% url 'shop:home' %}" method="get">
            <input name="search" value="{{ request.GET.search }}" type="text" placeholder="Search...">
            <button type="submit"><span class="icon_search"></span></button>
        </form>
        <a style="color: black" href="{% url 'shop:home' %}">Clear filter</a>
    </div>
    <div class="shop__sidebar__accordion">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__categories">
                            <ul class="nice-scroll">
                                {% for category in categories %}
                                    <li><a onclick="addUrlParameter('cat', {{ category.pk }})"
                                           class="{% if request.GET.cat == category.pk|stringformat:'i' %}text-dark{% endif %}">{{ category.name }}
                                        ({{ category.products.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                </div>
                <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__brand">
                            <ul>
                                {% for brand in brands %}
                                    <li><a class="{% if request.GET.brand == brand.pk|stringformat:'i' %}text-dark{% endif %}" onclick="addUrlParameter('brand', {{ brand.pk }})">{{ brand.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                </div>
                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__price">
                           <input type="text" class="js-range-slider" name="my_range" value="" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            {% for size in sizes %}
                                <a style="{% if request.GET.size == size.pk|stringformat:'i' %}background: #000; color: #fff;{% endif %}"
                                   onclick="addUrlParameter('size', {{ size.pk }})">{{ size.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                </div>
                <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__color">
                            {% for color in colors %}
                                <label style="background-color: {{ color.code }}" for="{{ color.code }}">
                                    <input onclick="addUrlParameter('color', {{ color.pk }})" type="radio" id="{{ color.code }}">
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            {% for tag in tags %}
                                <a style="{% if request.GET.tag == tag.pk|stringformat:'i' %}background: #000; color: #fff;{% endif %}"
                                   onclick="addUrlParameter('tag', {{ tag.pk }})">#{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>